#!/bin/bash

# Master file for all bash configutation.  Keep it in bin directory.
# copy ~/bin/.bash_profile to you home directory.  It sources this file.

# utility function
is_interactive_shell() {
    # Check if the shell is interactive
    if [[ $- == *i* ]]; then
        echo "This is an interactive shell"
    fi
}
#is_interactive_shell

iecho() {
    if [[ $- == *i* ]]; then
        echo "$@"
    fi
}

#iecho "This is an interactive shell"

iecho "sourcing bash_profile_bin"

#echo "home dir: $HOME"
iecho "sourcing profile_bryan" && source ~/bin/profile_bryan # sources other bash settings, especially dev environment-related.

#bash_work is now retired.
#[[ -s "$HOME/bin/bash_work" ]] && echo "sourcing bash_work" && source ~/bin/bash_work # source work related shell settings

# Copied this from bashstrap so I can customimze. it.  Uncomment or source the next line to go back to the original bashstrap.
#source ~/bin/bashstrap/.bash_profile

# load aliases
source ~/bin/.alias_bash.sh

# load 1Password CLI plugins
# TODO: fix 1Password CLI to work
if [ -f /Users/bryan/.config/op/plugins.sh ]; then
    source /Users/bryan/.config/op/plugins.sh
fi

### Misc

# Only show the current directory's name in the tab (DISABED for Timing)
#export PROMPT_COMMAND='echo -ne "\033]0;${PWD##*/}\007"'

# add completions (which may or may not be installed)

# brew completions
if [ -f $(brew --prefix)/etc/bash_completion.d/brew ]; then
    . $(brew --prefix)/etc/bash_completion.d/brew
fi

# git-extras completions
if [ -f $(brew --prefix)/etc/bash_completion.d/git-extras ]; then
    . $(brew --prefix)/etc/bash_completion.d/git-extras
fi

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
# disabling as I'm not using gvm for now
#[[ -s "/Users/bgebhardt/.gvm/bin/gvm-init.sh" ]] && source "/Users/bgebhardt/.gvm/bin/gvm-init.sh"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
#echo "initing sdkman"
#export SDKMAN_DIR="$HOME/.sdkman"
#[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

