#!/bin/bash

# Master file for all bash configutation.  Keep it in bin directory.
# copy ~/bin/.bash_profile to you home directory.  It sources this file.

echo "sourcing bash_profile_warp"

# Does nothing for now
# Note: I use the default warp prompt, which is pretty good.

# Change this symbol to something sweet.
# (http://en.wikipedia.org/wiki/Unicode_symbols)
#➡️❓✏️☞ # other potential symbols I kind of liked
symbol="⚡ "

# for more docs see [Bash Prompt Escape Sequences]( http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/bash-prompt-escape-sequences.html )
#export PS1="\[\t\][\!] \[${MAGENTA}\]\u \[$RESET\]in \[$GREEN\]\w\[$RESET\]\$([[ -n \$(git branch 2> /dev/null) ]] && echo \" on \")\[$PURPLE\]\$(parse_git_branch)\[$RESET\]$symbol\[$RESET\]"
#export PS1="\[\t\][\!] \[${MAGENTA}\]\u \[$RESET\]in \[$GREEN\]\w\[$RESET\]\$([[ -n \$(git branch 2> /dev/null) ]] && echo \" on \")\[$PURPLE\]\$(parse_git_branch)\[$RESET\] :"
#export PS1="\[\t\][\!] \[${MAGENTA}\]\u \[$RESET\]in \[$GREEN\]\w\[$RESET\]\$ :"
#export PS2="\[$ORANGE\]→ \[$RESET\]"
