#!/bin/bash
#
# generate-install-scripts.sh
# Given a tier manifest, generates subset install scripts that mirror the patterns
# in setup/homebrew/{brew.sh,brew-cask.sh} and setup/appstore/mas.sh.
#
# For each app in the selected tier(s):
#   - install_type "brew": grep brew-cask.sh for matching `brew install <cask>` line
#   - install_type "mas":  grep mas.sh for matching `mas install <id>` line
#   - install_type "other": cross-reference brew-cask.sh / mas.sh by normalized name;
#                            if a match (active OR commented) exists, include it and
#                            log to promotions.txt. Otherwise write to manual.txt.
#
# Output: <snapshot_dir>/tiers/install/install-<tier>-<type>.sh
#
# Usage: generate-install-scripts.sh [--tier essentials|regular|all] [snapshot_dir]

set -euo pipefail

TIER_LEVEL="essentials"
TARGET_SNAPSHOT_DIR=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --tier)
            TIER_LEVEL="$2"
            shift 2
            ;;
        -h|--help)
            sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            TARGET_SNAPSHOT_DIR="$1"
            shift
            ;;
    esac
done

case "$TIER_LEVEL" in
    essentials|regular|all) ;;
    *) echo "Error: --tier must be essentials, regular, or all" >&2; exit 1 ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$(dirname "$SCRIPT_DIR")/config.sh"
if [[ -f "$CONFIG_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"
fi

if ! command -v jq &>/dev/null; then
    echo "Error: jq is required." >&2
    exit 1
fi

SETUP_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BREW_SH="$SETUP_ROOT/homebrew/brew.sh"
BREW_CASK_SH="$SETUP_ROOT/homebrew/brew-cask.sh"
MAS_SH="$SETUP_ROOT/appstore/mas.sh"
OTHER_SH="$SETUP_ROOT/appstore/install-other-apps.sh"

for f in "$BREW_SH" "$BREW_CASK_SH" "$MAS_SH"; do
    [[ -f "$f" ]] || { echo "Error: source script not found: $f" >&2; exit 1; }
done

# Resolve snapshot dir
if [[ -z "$TARGET_SNAPSHOT_DIR" ]]; then
    SNAPSHOT_BASE=$(get_snapshot_dir 2>/dev/null || echo "$HOME/bin/setup/state-sync/snapshots")
    TARGET_SNAPSHOT_DIR=$(find "$SNAPSHOT_BASE" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | sort | tail -1)
    if [[ -z "$TARGET_SNAPSHOT_DIR" ]]; then
        echo "Error: no snapshot dirs found under $SNAPSHOT_BASE" >&2
        exit 1
    fi
fi

TIERS_DIR="$TARGET_SNAPSHOT_DIR/tiers"
INSTALL_DIR="$TIERS_DIR/install"
mkdir -p "$INSTALL_DIR"

# Determine which tiers to include
INCLUDED_TIERS=()
case "$TIER_LEVEL" in
    essentials) INCLUDED_TIERS=("essentials") ;;
    regular)    INCLUDED_TIERS=("essentials" "regular") ;;
    all)        INCLUDED_TIERS=("essentials" "regular" "rare") ;;
esac

echo "Snapshot:  $TARGET_SNAPSHOT_DIR" >&2
echo "Tier:      $TIER_LEVEL (includes: ${INCLUDED_TIERS[*]})" >&2
echo "Output:    $INSTALL_DIR" >&2

# Combine selected tier apps into one stream
APPS_JSON=$(mktemp)
trap 'rm -f "$APPS_JSON"' EXIT
{
    for tier in "${INCLUDED_TIERS[@]}"; do
        jq -c '.apps[]' "$TIERS_DIR/tier-${tier}.json"
    done
} | jq -s '.' > "$APPS_JSON"

TOTAL_APPS=$(jq 'length' "$APPS_JSON")
echo "Total apps in selected tier: $TOTAL_APPS" >&2

# Output files
BREW_OUT="$INSTALL_DIR/install-${TIER_LEVEL}-brew.sh"
CASK_OUT="$INSTALL_DIR/install-${TIER_LEVEL}-brew-cask.sh"
MAS_OUT="$INSTALL_DIR/install-${TIER_LEVEL}-mas.sh"
MANUAL_OUT="$INSTALL_DIR/install-${TIER_LEVEL}-manual.txt"
PROMOTIONS_OUT="$INSTALL_DIR/install-${TIER_LEVEL}-promotions.txt"

GEN_HEADER="# Generated by generate-install-scripts.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Tier: ${TIER_LEVEL}
# Source snapshot: ${TARGET_SNAPSHOT_DIR}
# DO NOT EDIT — regenerate from the source by running generate-install-scripts.sh
"

# Initialize output files
{ echo "#!/usr/bin/env bash"; echo "set -e"; echo "$GEN_HEADER"; echo "# Filtered subset of: $BREW_SH"; echo ""; } > "$BREW_OUT"
{ echo "#!/usr/bin/env bash"; echo "set -e"; echo "$GEN_HEADER"; echo "# Filtered subset of: $BREW_CASK_SH"; echo ""; } > "$CASK_OUT"
{ echo "#!/usr/bin/env bash"; echo "set -e"; echo "$GEN_HEADER"; echo "# Filtered subset of: $MAS_SH"; echo "# NOTE: requires being signed into the Mac App Store first."; echo ""; } > "$MAS_OUT"
{
    echo "# Manual install list — Tier: ${TIER_LEVEL}"
    echo "# Generated $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# These apps need manual install (no brew/mas managed install detected)."
    echo "# Format: <app_name>\\t<original_path>\\t<url_hint>"
    echo ""
} > "$MANUAL_OUT"
{
    echo "# Promotions — Tier: ${TIER_LEVEL}"
    echo "# Generated $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# These apps were installed manually (\"other\") but a brew/mas line was found"
    echo "# in the source scripts. The matching line has been added to the install script."
    echo "# If you don't want a particular promotion, remove the line from the install script."
    echo ""
} > "$PROMOTIONS_OUT"

# Helpers
normalize() {
    # lowercase, spaces -> hyphens, strip trailing version suffix " 3" etc.
    echo "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[[:space:]]+/-/g'
}

# Match a brew cask line (active or commented) — returns line WITHOUT the leading "# "
find_brew_cask_line() {
    local cask="$1"
    { grep -E "^[[:space:]]*#?[[:space:]]*brew install (--cask )?${cask}([[:space:]]|$|#)" "$BREW_CASK_SH" || true; } \
        | head -1 | sed -E 's/^[[:space:]]*#[[:space:]]?//'
}

find_brew_formula_line() {
    local name="$1"
    { grep -E "^[[:space:]]*#?[[:space:]]*brew install ${name}([[:space:]]|$|#)" "$BREW_SH" || true; } \
        | head -1 | sed -E 's/^[[:space:]]*#[[:space:]]?//'
}

find_mas_line_by_id() {
    local id="$1"
    { grep -E "^[[:space:]]*#?[[:space:]]*mas install ${id}([[:space:]]|$|#)" "$MAS_SH" || true; } \
        | head -1 | sed -E 's/^[[:space:]]*#[[:space:]]?//'
}

find_mas_line_by_name() {
    local name="$1"
    # Match comments like "mas install 1234567890 # AppName"
    { grep -iE "mas install [0-9]+.*${name}" "$MAS_SH" || true; } \
        | head -1 | sed -E 's/^[[:space:]]*#[[:space:]]?//'
}

find_other_url() {
    local name="$1"
    { grep -iE "${name}" "$OTHER_SH" 2>/dev/null || true; } \
        | { grep -oE 'https?://[^"'"'"' ]+' || true; } | head -1
}

# Process each app
brew_count=0
cask_count=0
mas_count=0
manual_count=0
promo_count=0

while IFS= read -r app_record; do
    name=$(jq -r '.name' <<<"$app_record")
    install_type=$(jq -r '.install_type' <<<"$app_record")
    path=$(jq -r '.path' <<<"$app_record")
    tier=$(jq -r '.tier' <<<"$app_record")

    case "$install_type" in
        brew)
            cask=$(jq -r '.cask_name // empty' <<<"$app_record")
            if [[ -n "$cask" ]]; then
                line=$(find_brew_cask_line "$cask")
                if [[ -n "$line" ]]; then
                    echo "$line" >> "$CASK_OUT"
                    cask_count=$((cask_count + 1))
                else
                    # Cask exists in Caskroom but not in our brew-cask.sh — add a fresh line
                    echo "brew install --cask $cask  # [tier:$tier] auto-added (not in $BREW_CASK_SH)" >> "$CASK_OUT"
                    cask_count=$((cask_count + 1))
                fi
            fi
            ;;
        mas)
            mas_id=$(jq -r '.mas_id // empty' <<<"$app_record")
            if [[ -n "$mas_id" ]]; then
                line=$(find_mas_line_by_id "$mas_id")
                if [[ -z "$line" ]]; then
                    line=$(find_mas_line_by_name "$name")
                fi
                if [[ -n "$line" ]]; then
                    echo "$line" >> "$MAS_OUT"
                else
                    echo "mas install $mas_id  # $name [tier:$tier] auto-added (not in $MAS_SH)" >> "$MAS_OUT"
                fi
                mas_count=$((mas_count + 1))
            fi
            ;;
        other)
            # Try to promote: look up the app in brew-cask.sh / mas.sh by normalized name
            norm=$(normalize "$name")
            promoted=false

            cask_line=$(find_brew_cask_line "$norm")
            if [[ -n "$cask_line" ]]; then
                echo "$cask_line  # promoted from manual: $name" >> "$CASK_OUT"
                printf 'cask\t%s\t%s\n' "$name" "$norm" >> "$PROMOTIONS_OUT"
                cask_count=$((cask_count + 1))
                promo_count=$((promo_count + 1))
                promoted=true
            else
                # Try formula too in case some non-cask brews are GUI-installed manually
                formula_line=$(find_brew_formula_line "$norm")
                if [[ -n "$formula_line" ]]; then
                    echo "$formula_line  # promoted from manual: $name" >> "$BREW_OUT"
                    printf 'brew\t%s\t%s\n' "$name" "$norm" >> "$PROMOTIONS_OUT"
                    brew_count=$((brew_count + 1))
                    promo_count=$((promo_count + 1))
                    promoted=true
                fi
            fi

            if [[ "$promoted" == "false" ]]; then
                mas_line=$(find_mas_line_by_name "$name")
                if [[ -n "$mas_line" ]]; then
                    echo "$mas_line  # promoted from manual: $name" >> "$MAS_OUT"
                    printf 'mas\t%s\t-\n' "$name" >> "$PROMOTIONS_OUT"
                    mas_count=$((mas_count + 1))
                    promo_count=$((promo_count + 1))
                    promoted=true
                fi
            fi

            if [[ "$promoted" == "false" ]]; then
                url=$(find_other_url "$name")
                printf '%s\t%s\t%s\n' "$name" "$path" "${url:-(no URL hint)}" >> "$MANUAL_OUT"
                manual_count=$((manual_count + 1))
            fi
            ;;
    esac
done < <(jq -c '.[]' "$APPS_JSON")

# Final summary
SUMMARY="$INSTALL_DIR/summary-${TIER_LEVEL}.txt"
{
    echo "========================================"
    echo "Install Script Generation — Tier: ${TIER_LEVEL}"
    echo "========================================"
    echo "Generated: $(date)"
    echo "Snapshot:  $TARGET_SNAPSHOT_DIR"
    echo ""
    echo "Output files:"
    echo "  $BREW_OUT          ($brew_count formulae)"
    echo "  $CASK_OUT          ($cask_count casks)"
    echo "  $MAS_OUT           ($mas_count mas apps)"
    echo "  $MANUAL_OUT        ($manual_count manual entries)"
    echo "  $PROMOTIONS_OUT    ($promo_count promotions from 'other' to brew/mas)"
    echo ""
    echo "Total apps processed: $TOTAL_APPS"
    echo "Total install actions: $((brew_count + cask_count + mas_count + manual_count))"
    echo ""
    if [[ "$promo_count" -gt 0 ]]; then
        echo "--- Promotions (manual installs that have a brew/mas line available) ---"
        head -20 "$PROMOTIONS_OUT" | tail -n +5
        echo ""
    fi
    echo "--- Manual installs still required ---"
    tail -n +6 "$MANUAL_OUT" | head -20
} > "$SUMMARY"

chmod +x "$BREW_OUT" "$CASK_OUT" "$MAS_OUT"

echo "" >&2
echo "Done. Summary:" >&2
cat "$SUMMARY"
